import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'

export default function Home() {

  const handleOnBannerClick = () => {
    alert('You clicked the banner button!')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connosisseur</title>
        <meta name="Discover your local coffee shops!" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner 
          buttonText="View stores nearby" 
          handleOnClick={handleOnBannerClick}
          />
      </main>
    </div>
  )
}
