import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from '../components/banner'
import Card from '../components/card'
import { fetchCoffeeStores } from '../lib/coffee-stores'


// * Server Side Code below
export async function getStaticProps() {

  const coffeeStores = await fetchCoffeeStores();
  return {
    props: {
      coffeeStores
    },
  };
}

// * Client Side Code below
export default function Home(props) {
  const handleOnBannerClick = () => {
    alert('You clicked the banner button!')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connosisseur</title>
        <meta name="Discover your local coffee shops!" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerClick}
        />
        <div className={styles.heroImage}>
          <Image src="/static/hero-image.png" width={700} height={400} alt="Hero image" />
        </div>
        {props.coffeeStores && props.coffeeStores.length > 0 &&
          <>
            <h2 className={styles.heading2}>Toronto shops</h2>

            <div className={styles.cardLayout}>
              {props.coffeeStores && props.coffeeStores.map((store) => {
                return (
                  <Card
                    key={store.fsq_id}
                    name={store.name}
                    imgUrl={store.imgUrl || 'https://images.unsplash.com/photo-1504753793650-d4a2b783c15e?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=2000&q=80'}
                    href={`/coffee-store/${store.fsq_id}`}
                    altText={store.name}
                    className={styles.card}
                  />
                )
              })
              }
            </div>
          </>}
      </main>
    </div>
  )
}
